name: Update HTML Content from Markdown

on:
  push:
    paths:
      - 'content/**'
    branches: [ main ]

jobs:
  update-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Update HTML content
      run: npm run update-content
      
    - name: Commit changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add *.html
        git commit -m "Update HTML from Markdown" || exit 0
        
    - name: Push changes
      run: git push
